name: expense_tracker
description: "This Expense Tracker was made by Yash Jain, created for personal needs"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
   android: true
   ios: true
   image_path: "assets/icon/app_icon.png" # Path to your icon image

flutter:

  uses-material-design: true

